project_name: 'OCR'
experiment_name: 'exp8'
num_classes: 24
n_epochs: 100
accelerator: 'gpu'
device: 0
monitor_metric: 'valid_ctc_loss'
monitor_mode: 'min'
weights_path: './models/ts_script_model/final_ocr.pt'

model_kwargs:
  backbone_name: 'resnet18'
  pretrained: true
  cnn_out_index: 3
  cnn_output_size: 256
  cnn_output_height: 6
  rnn_features_num: 48
  rnn_hidden_size: 64
  rnn_num_layers: 4
  rnn_dropout: 0.1
  rnn_bidirectional: true
  num_classes: 11

optimizer: 'torch.optim.AdamW'
optimizer_kwargs:
  lr: 1e-3
  weight_decay: 1e-5

scheduler: 'torch.optim.lr_scheduler.ReduceLROnPlateau'
scheduler_kwargs:
  mode: 'min'
  factor: 0.3
  patience: 20
  min_lr: 1e-5

losses:
  - name: 'ctc'
    weight: 1.0
    loss_fn: 'torch.nn.CTCLoss'
    loss_kwargs: {}

data_config:
  data_path: './data'
  batch_size: 48
  num_iterations: 100
  n_workers: 4
  width: 416
  height: 96
  vocab: '0123456789'
  text_size: 13